from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package="deptrum-ros-driver-nebula",
            executable="nebula_node",
            namespace="nebula_1",
            parameters=[
                {"rgb_enable": True,
                 "ir_enable": True,
                 "depth_enable": True,
                 "flag_enable": True,
                 "point_cloud_enable": True,
                 "device_numbers": 2,
                 "slam_mode": 1,
                 "boot_order": 1,
                 "resolution_mode_index": 0,
                 "usb_port_number": "",
                 "serial_number": "",
                 "rgbd_enable": False,
                 "exposure_enable": False,
                 "exposure_time": 1000,
                 "undistortion_enable": False,
                 "filter_type": 1,
                 "mtof_filter_level": 1,
                 "stof_filter_level": 1,
                 "outlier_point_removal_flag": True,
                 "heart_enable": False,
                 "update_file_path": "",
                 "log_dir": "/tmp/",
                 "heart_timeout_times": 8,
                 "stream_sdk_log_enable": True,
                 "ir_fps": 25,
                 }
            ],
            arguments=None,
            output="screen",   
        ),
        Node(
            package="deptrum-ros-driver-nebula",
            executable="nebula_node",
            namespace="nebula_2",
            parameters=[
                {"rgb_enable": True,
                 "ir_enable": True,
                 "depth_enable": True,
                 "flag_enable": True,
                 "point_cloud_enable": True,
                 "device_numbers": 2,
                 "slam_mode": 1,
                 "boot_order": 2,
                 "resolution_mode_index": 0,
                 "usb_port_number": "",
                 "serial_number": "",
                 "rgbd_enable": False,
                 "exposure_enable": False,
                 "exposure_time": 1000,
                 "undistortion_enable": False,
                 "filter_type": 1,
                 "mtof_filter_level": 1,
                 "stof_filter_level": 1,
                 "outlier_point_removal_flag": True,
                 "heart_enable": False,
                 "update_file_path": "",
                 "log_dir": "/tmp/",
                 "heart_timeout_times": 8,
                 "stream_sdk_log_enable": True,
                 "ir_fps": 25,
                 }
            ],
            arguments=None,
            output="screen",   
        )
    ])