function(download RESULT TARGET_URL TARGET_FILENAME INSTALL_PATH TARGET_MD5)
  message(STATUS "Download ${TARGET_FILENAME} from ${TARGET_URL}")
  if("${TARGET_MD5}" STREQUAL "" OR "${TARGET_MD5}" STREQUAL "${STAGING_MD5}")
    file(DOWNLOAD ${TARGET_URL} ${INSTALL_PATH}/${TARGET_FILENAME} STATUS ResultList)
  else()
    file(DOWNLOAD ${TARGET_URL} ${INSTALL_PATH}/${TARGET_FILENAME} STATUS ResultList EXPECTED_MD5 ${TARGET_MD5})
  endif()
  list(GET ResultList 0 result)
  set(${RESULT} "${result}" PARENT_SCOPE)
  if(${result} EQUAL 0)
    get_filename_component(TARGET_EXT ${INSTALL_PATH}/${TARGET_FILENAME} EXT)
    if("${TARGET_EXT}" MATCHES ".*\\.tar" OR "${TARGET_EXT}" MATCHES ".*\\.tar\\.gz" OR "${TARGET_EXT}" MATCHES ".*\\.tgz")
      set(UNPACK_CMD tar xf ./${TARGET_FILENAME})
    elseif(WIN32 AND "${TARGET_EXT}" MATCHES ".*\\.zip")
      set(UNPACK_CMD powershell "(Expand-Archive -Path ./${TARGET_FILENAME} -DestinationPath ./)")
    elseif("${TARGET_EXT}" MATCHES ".*\\.zip")
      set(UNPACK_CMD unzip -q ${TARGET_FILENAME})
    else()
      message("not known the suffix:${TARGET_EXT}")
    endif()
    execute_process(COMMAND ${UNPACK_CMD} WORKING_DIRECTORY "${INSTALL_PATH}" ERROR_VARIABLE ErrorInfo)
    string(COMPARE NOTEQUAL "${ErrorInfo}" "" Result)
    if(Result)
      message(FATAL_ERROR "${ErrorInfo}")
    else()
      file(REMOVE ${INSTALL_PATH}/${TARGET_FILENAME})
    endif()
  else()
    message(FATAL_ERROR "${TARGET_URL} doesn't exist.")
  endif()
endfunction(download)

function(download_3rdparty LIBRARY_NAME TARGET_EXT TARGET_MD5)
  set(TARGET_NAME "${LIBRARY_NAME}")
  set(LOCAL_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}")
  set(REMOTE_LIB_PATH "http://192.168.104.3/data/third_party/${SYSTEM_PLATFORM}")
  if(NOT EXISTS "${LOCAL_LIB_PATH}/${TARGET_NAME}")
    download(RESULT ${REMOTE_LIB_PATH}/${TARGET_NAME}.${TARGET_EXT} ${TARGET_NAME}.${TARGET_EXT} ${LOCAL_LIB_PATH} "")
    if(${RESULT} GREATER 0)
      message(FATAL_ERROR "Failed to download ${REMOTE_LIB_PATH}/${TARGET_NAME}.${TARGET_EXT}. Error code: ${RESULT}")
    endif()
  endif()
endfunction(download_3rdparty)

function(download_sdk NAME VERSION)
  set(prefix ARG)
  set(options DOWNLOAD_SYMBOL)
  set(oneValueArgs "")
  set(multiValueArgs "")
  cmake_parse_arguments("${prefix}" "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  set(SDK_NAS_PATH ${NAME})

  string(REPLACE "/" "-" NAME_HYPHEN ${NAME})
  string(TOUPPER ${NAME_HYPHEN} UPPER_NAME)
  string(REPLACE "-" "_" UPPER_NAME_UNDERLINE ${UPPER_NAME})
  set(SDK_PACKAGE_NAME ${NAME_HYPHEN})


  set(SDK_PACKAGE_NAME ${SDK_PACKAGE_NAME}-${SYSTEM_PLATFORM}-${VERSION})
  set(SDK_NAS_PATH ${SDK_NAS_PATH}/release/${SYSTEM_PLATFORM})

  set(SDK_PACKAGE_NAME "${SDK_PACKAGE_NAME}-18.04")

  set(TARGET_EXT "tar.gz")

  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/${SDK_PACKAGE_NAME}")
    message(STATUS "${SDK_PACKAGE_NAME} exist！")
  else()
    set(SDK_URL http://192.168.104.3/data/ci_release/${SDK_NAS_PATH}/${SDK_PACKAGE_NAME}.${TARGET_EXT})
    download(RESULT ${SDK_URL} ${SDK_PACKAGE_NAME}.${TARGET_EXT} ${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME} "")
    if(NOT ${RESULT} EQUAL 0)
      message(FATAL_ERROR "${SDK_URL} doesn't exist.")
      return()
    endif()
  endif()

  set(${UPPER_NAME_UNDERLINE}_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/${SDK_PACKAGE_NAME}" PARENT_SCOPE)
  set(${UPPER_NAME_UNDERLINE}_INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/${SDK_PACKAGE_NAME}/include" PARENT_SCOPE)
  set(${UPPER_NAME_UNDERLINE}_STATIC_LIBRARY_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/${SDK_PACKAGE_NAME}/lib" PARENT_SCOPE)
  set(${UPPER_NAME_UNDERLINE}_SHARED_LIBRARY_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/${SDK_PACKAGE_NAME}/bin" PARENT_SCOPE)
endfunction(download_sdk)



function(download_file TARGET_PATH TARGET_URL TARGET_MD5)
  if(EXISTS ${TARGET_PATH})
    file(MD5 ${TARGET_PATH} LOCAL_MD5)
    if(${LOCAL_MD5} STREQUAL ${TARGET_MD5})
      return()
    endif()
  endif()
  message(STATUS "Download ${TARGET_PATH} from ${TARGET_URL}")
  file(DOWNLOAD ${TARGET_URL} ${TARGET_PATH} STATUS ResultList EXPECTED_MD5 ${TARGET_MD5})
  list(GET ResultList 0 result)
  if(NOT ${result} EQUAL 0)
    message(FATAL_ERROR "${TARGET_URL} doesn't exist.")
  endif()
endfunction()
