set(LIB_VERSION 2.2.2)
set(GFlags_FOUND FALSE)
if(${SYSTEM_PLATFORM} STREQUAL "linux-x86_64")
  set(TARGET_MD5 d56102fc77877151816cb4acb1f8ef3a)
elseif(${SYSTEM_PLATFORM} STREQUAL "linux-aarch64")
  set(TARGET_MD5 fe5cbfbe6b46698138b8e89d67773615)
endif()
set(LIB_NAME "gflags-${LIB_VERSION}")
if(WIN32)
  set(TARGET_EXT "zip")
elseif(${SYSTEM_PLATFORM} STREQUAL "linux-armv7l")
  set(TARGET_EXT "tar.gz")
else()
  set(TARGET_EXT "tgz")
endif()

download_3rdparty(${LIB_NAME} ${TARGET_EXT} "")

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/gflags-${LIB_VERSION}/include/gflags/gflags.h" )
  set(GFlags_FOUND TRUE)
  set(GFlags_INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/gflags-${LIB_VERSION}/include")
  set(GFlags_LIBRARY_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/${EXTERNAL_DIR_NAME}/gflags-${LIB_VERSION}/lib-static")
  if(WIN32)
    set(POSTFIX $<$<CONFIG:Debug>:_debug>)
    set(GFlags_LIBRARY gflags_static${POSTFIX} shlwapi)
  else()
    set(GFlags_LIBRARY gflags)
  endif()
  if((NOT WIN32) AND ENABLE_LD_GROUP)
    set(GFlags_LIBRARY
        -Wl,--start-group
        ${GFlags_LIBRARY}
        -Wl,--end-group
       )
  endif()
endif()
unset(TARGET_MD5)

if(GFlags_FOUND)
  message(STATUS "GFlags library status:")
  message(STATUS "    include path: ${GFlags_INCLUDE_DIRS}")
  message(STATUS "    library path: ${GFlags_LIBRARY_DIRS}")
  message(STATUS "    libraries: ${GFlags_LIBRARY}")
  include_directories(SYSTEM ${GFlags_INCLUDE_DIRS})
  link_directories(${GFlags_LIBRARY_DIRS})
else()
  message(FATAL_ERROR "Failed to find GFlags!")
endif(GFlags_FOUND)
