from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package="deptrum-ros-driver-stellar400",
            executable="stellar400_node",
            namespace="stellar_1",
            parameters=[
                {"rgb_enable": True,
                 "ir_enable": True,
                 "depth_enable": True,
                 "point_cloud_enable": True,
                 "device_numbers": 2,
                 "boot_order": 1,
                 "ir_fps": 25,
                 "rgb_fps": 25,
                 "resolution_mode_index": 0,
                 "usb_port_number": "",
                 "serial_number": "",
                 "rgbd_enable": False,
                 "exposure_enable": False,
                 "exposure_time": 1000,
                 "undistortion_enable": False,
                 "filter_type": 1,
                 "depth_frequency_fusion_threshold": 120.0,
                 "ir_frequency_fusion_threshold": 24,
                 "ratio_scatter_filter_threshold": 0.025,
                 "outlier_point_removal_flag": True,
                 "heart_enable": True,
                 "update_file_path": "",
                 "log_dir": "/tmp/",
                 "heart_timeout_times": 8,
                 "stream_sdk_log_enable": True,
                 }
            ],
            arguments=None,
            output="screen",   
        ),
        Node(
            package="deptrum-ros-driver-stellar400",
            executable="stellar400_node",
            namespace="stellar_2",
            parameters=[
                {"rgb_enable": True,
                 "ir_enable": True,
                 "depth_enable": True,
                 "point_cloud_enable": True,
                 "device_numbers": 2,
                 "boot_order": 2,
                 "ir_fps": 25,
                 "rgb_fps": 25,
                 "resolution_mode_index": 0,
                 "usb_port_number": "",
                 "serial_number": "",
                 "rgbd_enable": False,
                 "exposure_enable": False,
                 "exposure_time": 1000,
                 "undistortion_enable": False,
                 "filter_type": 1,
                 "depth_frequency_fusion_threshold": 120.0,
                 "ir_frequency_fusion_threshold": 24,
                 "ratio_scatter_filter_threshold": 0.025,
                 "outlier_point_removal_flag": True,
                 "heart_enable": True,
                 "update_file_path": "",
                 "log_dir": "/tmp/",
                 "heart_timeout_times": 8,
                 "stream_sdk_log_enable": True,
                 }
            ],
            arguments=None,
            output="screen",   
        )
    ])